#!/bin/bash
#move every .bin or .nrm (resulted from ocropus-nlbin) from the directories
#contained here to a single directory

filename=$1 #"bin" or "nrm"

#creates the directoyry if there's none calle $filename
if [ ! -d $filename ]; then 
  mkdir -p $filename;
fi


#for every directory (not subdirectories) here
for D in */;do
	for i in *''$D'0001.'$filename'.png'; do #for every .bin or .nrm
		mv $i ''$filename'/'${D%.ocropus/}'.'$filename'.png'; #move to the created directory
	done;
done;