#!/bin/bash
#apply ocrevalUAtion to folder or files

#ground_truth=$1
#ocr=$2
ocr='.'
groundtruth="/home/banshee/Pictures/ocr-images/Database/groundtruth"


java -cp /home/banshee/ocrevalUAtion-master/target/ocrevaluation.jar eu.digitisation.Main -gt $groundtruth -ocr $ocr
