#!/bin/bash
#apply all ocropus' tools on the file


filename=$1
path=$2
#model=$3

# perform binarization
ocropus-nlbin $filename -n -Q 4 -o $path

# perform page layout analysis
ocropus-gpageseg -n -Q 4 "$path/????.bin.png"

# perform text line recognition
#ocropus-rpred -n -m $model -Q 4 "$path/????/??????.bin.png"
ocropus-rpred -n -Q 4 -m *.pyrnn.gz "$path/????/??????.bin.png"

# generate HTML output
ocropus-hocr "$path/????.bin.png" -o $path.html
