#!/bin/bash
#apply all ocropus' tools on the file

filename=$1
path=$2

# perform binarization
ocropus-nlbin $filename -n -m 0 -Q 4 -o $path

# perform page layout analysis
ocropus-gpageseg -n -Q 4 ''$path'/????.bin.png'

# perform text line recognition
ocropus-rpred -n -Q 4 ''$path'/????/??????.bin.png'

# generate HTML output
ocropus-hocr ''$path'/????.bin.png' -o $path.html

