#!/bin/bash
#convert a multipage pdf into mutiple .tiffs (one per page)

dpi=$1 #do not use values above your hardware resolution
input_file=$2

#creates "Xdpi	" directory if doesn't exist
if [ ! -d ''$dpi'dpi' ]; then
  mkdir -p ''$dpi'dpi';
fi

gs -dNOPAUSE '-r'$dpi'' -sDEVICE=tiff24nc -dBATCH '-sOutputFile='$dpi'dpi/a%03d.tiff' $input_file