#!/bin/bash
#apply tesseract to every .tiff in the directory

#language=$1;

#creates "tesseract" directory if doesn't exist
if [ ! -d tesseract ]; then
  mkdir -p tesseract;
fi

for i in *.tiff; do
	#tesseract $i tesseract/"${i%.tiff}".tess -l eng+"$language" #calls tesseract (takes .tiff out from output's name)
	tesseract $i tesseract/"${i%.tiff}".tess #calls tesseract (takes .tiff out from output's name)
done;
